package vistas;

import Modelo.Ingrediente;
import Modelo.ModeloIngEx;
import Modelo.Ingpla;
import accesodatos.PlatilloJpaController;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import Modelo.ModeloPlat;
import Modelo.ModeloTI;
import Modelo.Modelo_Ing_Plat;
import Modelo.ModeloTablaSelIng;
import Modelo.Platillo;
import Modelo.TipoIngrediente;
import accesodatos.IngplaJpaController;
import accesodatos.IngredienteJpaController;
import javax.swing.ComboBoxModel;
import javax.swing.JComboBox;
import accesodatos.TipoIngredienteJpaController;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author aime
 */
public class Platillos extends javax.swing.JDialog {
    private String descripionTI[];
    private ModeloTI modeloIng;
    private Modelo_Ing_Plat  modeloIP;
    private Platillo platillo;
    private Ingpla ingPlatillo;
    private TipoIngrediente tIngrediente;
    private Ingrediente ingrediente;
    private List<Platillo> platillos;
    private List<Ingpla> Ingplatillos;
    private ModeloPlat modeloPlat;
    private ModeloIngEx modeloIngEx;
    private ArrayList<Ingrediente> index;
    private ArrayList<Ingpla> temp;
    private List<Ingrediente> IngredientesJC;
    private TipoIngredienteJpaController cTipoIng;
    private IngplaJpaController cIngPla;
    private IngredienteJpaController cIngrediente;
    private List<TipoIngrediente> tiposIng;
    private List<Ingrediente> Ingredientes;
    private List<Ingpla> ingPlat;
    private PlatilloJpaController cPlatillo;
    private IngplaJpaController cIngPlatillo;
    

    /**
     * Creates new form Platillos
     */
    public Platillos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("ordenar_cafeteriaPU");
        cTipoIng = new TipoIngredienteJpaController(emf);
        cIngrediente = new IngredienteJpaController(emf);
        cIngPlatillo = new IngplaJpaController(emf);
        cPlatillo = new PlatilloJpaController(emf);
        cIngPla = new IngplaJpaController(emf);
        tiposIng = cTipoIng.findTipoIngredienteEntities();//en este se le pasó lo que tiene la base de datos tipo ingreidntes al list?
        Ingredientes = cIngrediente.findIngredienteEntities();
        IngredientesJC = cIngrediente.findIngredienteEntities();
        
        Ingplatillos=cIngPla.findIngplaEntities();
        platillos = cPlatillo.findPlatilloEntities();
        cargarTI();
        cargarIng();

        agregarPlatIng.setEnabled(false);
        termPlatIng.setEnabled(false);
        //ModeloTablaSelIng
        //ModeloTablaSelIng mTablaSelIng = new ModeloTablaSelIng(Ingredientes);
        //Botones de la interfaz del examen
        restaurarCant.setEnabled(false);
        regPlatIngEx.setEnabled(false);

        modeloPlat = new ModeloPlat(platillos);
        tPlatillos.setModel(modeloPlat);
        modeloIng = new ModeloTI(Ingredientes);
        tIngredientes.setModel(modeloIng);
        modeloIP=new Modelo_Ing_Plat(Ingplatillos);
        tablaIng_Plat.setModel(modeloIP);
        modeloIngEx = new ModeloIngEx(Ingredientes);
        tPlatIngEx.setModel(modeloIngEx);
        modeloIngEx.rellenar();

        //TIpoIng = new JComboBox<>(descripionTI);//.setModel(new ComboBoxModel<String>descripionTI);
    }

    private void cargarTI() {//
        //descripionTI = new String[tiposIng.size()];
        for (int nti = 0; nti < tiposIng.size(); nti++) {//for para recorrer el list de tipo de ingrediente
            //descripionTI[nti] = tiposIng.get(nti).getNombre();
            TipoIng.addItem(tiposIng.get(nti).getNombre());//al combo box se le añade lo que tiene el list tipo ingrediente
        }
    }

    private void cargarIng() {
        //descripionTI = new String[tiposIng.size()];
        for (int nti = 0; nti < Ingredientes.size(); nti++) {//for para recorre el list de ingredientes
            //descripionTI[nti] = tiposIng.get(nti).getNombre();
            ings.addItem(Ingredientes.get(nti).getNombre());// se le añade al combo box de la pestaña agregar platillo la de los ingredientes
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Nombre = new javax.swing.JTextField();
        Cantidad = new javax.swing.JSpinner();
        Unidad = new javax.swing.JComboBox<>();
        TipoIng = new javax.swing.JComboBox<>();
        agregar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tIngredientes = new javax.swing.JTable();
        aceptar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        nombrePlat = new javax.swing.JTextField();
        precioPlat = new javax.swing.JSpinner();
        existenciasPlat = new javax.swing.JSpinner();
        registrarPlat = new javax.swing.JButton();
        ings = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        cantIngP = new javax.swing.JSpinner();
        exisIngP = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        agregarPlatIng = new javax.swing.JButton();
        termPlatIng = new javax.swing.JButton();
        tiempoP = new javax.swing.JSpinner();
        porcionP = new javax.swing.JSpinner();
        unidadMP = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        unidadIngP = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tPlatillos = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        nombrePlatEx = new javax.swing.JTextField();
        precioPlatEx = new javax.swing.JSpinner();
        existenciasPlatEx = new javax.swing.JSpinner();
        tiempoPEx = new javax.swing.JSpinner();
        porcionPEx = new javax.swing.JSpinner();
        unidadMPEx = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tPlatIngEx = new javax.swing.JTable();
        regPlatEx = new javax.swing.JButton();
        regPlatIngEx = new javax.swing.JButton();
        restaurarCant = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaIng_Plat = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTabbedPane2.setBackground(new java.awt.Color(255, 255, 204));
        jTabbedPane2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTabbedPane2.setForeground(new java.awt.Color(255, 255, 204));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Goudy Old Style", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("Registar ingredientes");

        jLabel2.setText("Nombre: ");

        jLabel3.setText("Cantidad: ");

        jLabel4.setText("Unidad: ");

        jLabel5.setText("Tipo: ");

        Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreActionPerformed(evt);
            }
        });

        Cantidad.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 1000.0d, 1.0d));

        Unidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pza", "Kg", "Gr", "Litros", "Cajas" }));

        TipoIng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoIngActionPerformed(evt);
            }
        });

        agregar.setBackground(new java.awt.Color(255, 255, 0));
        agregar.setText("Agregar");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel3))))
                                .addGap(38, 38, 38)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Unidad, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TipoIng, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(44, 44, 44)
                                .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(174, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel1)
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Unidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TipoIng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(52, 52, 52)
                .addComponent(agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Agregar ingredientes", jPanel1);

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        tIngredientes.setBackground(new java.awt.Color(204, 255, 204));
        tIngredientes.setForeground(new java.awt.Color(102, 102, 102));
        tIngredientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tIngredientes);

        aceptar.setBackground(new java.awt.Color(255, 255, 0));
        aceptar.setForeground(new java.awt.Color(102, 102, 102));
        aceptar.setText("Aceptar");
        aceptar.setBorder(null);
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(274, 274, 274))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(153, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Mostrar ingredientes", jPanel3);

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));

        jLabel6.setFont(new java.awt.Font("Goudy Old Style", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setText("Formar platillo");

        jLabel7.setText("Nombre:");

        jLabel8.setText("Precio: ");

        jLabel9.setText("Existencias: ");

        nombrePlat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombrePlatActionPerformed(evt);
            }
        });

        precioPlat.setModel(new javax.swing.SpinnerNumberModel(20.0d, 20.0d, 1000.0d, 1.0d));
        precioPlat.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        existenciasPlat.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
        existenciasPlat.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        registrarPlat.setBackground(new java.awt.Color(255, 255, 0));
        registrarPlat.setForeground(new java.awt.Color(51, 51, 51));
        registrarPlat.setText("Registrar platillo");
        registrarPlat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarPlatActionPerformed(evt);
            }
        });

        ings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingsActionPerformed(evt);
            }
        });

        jLabel10.setText("Ingredientes");

        cantIngP.setModel(new javax.swing.SpinnerNumberModel(1.0d, 1.0d, 1000.0d, 1.0d));

        exisIngP.setText("_________");

        jLabel12.setText("Cantidad");

        agregarPlatIng.setBackground(new java.awt.Color(255, 255, 153));
        agregarPlatIng.setForeground(new java.awt.Color(51, 51, 51));
        agregarPlatIng.setText("Agregar");
        agregarPlatIng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarPlatIngActionPerformed(evt);
            }
        });

        termPlatIng.setBackground(new java.awt.Color(255, 255, 153));
        termPlatIng.setForeground(new java.awt.Color(51, 51, 51));
        termPlatIng.setText("Terminar");
        termPlatIng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                termPlatIngActionPerformed(evt);
            }
        });

        tiempoP.setModel(new javax.swing.SpinnerNumberModel(1, 1, 4, 1));

        porcionP.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        unidadMP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pza", "Kg", "Gr", "Litros", "Taza" }));

        jLabel13.setText("TIempo. ");

        jLabel14.setText("Porción:");

        jLabel15.setText("Unidad de medida:");

        unidadIngP.setText("_____");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(226, 226, 226))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(nombrePlat)
                                .addComponent(porcionP, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(unidadMP, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tiempoP, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(precioPlat, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(existenciasPlat, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(ings, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exisIngP)
                        .addGap(10, 10, 10)
                        .addComponent(unidadIngP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(cantIngP, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(agregarPlatIng)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(termPlatIng))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addComponent(registrarPlat, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addComponent(jLabel10)))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel6)
                .addGap(53, 53, 53)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombrePlat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tiempoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(porcionP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unidadMP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(7, 7, 7)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(precioPlat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(existenciasPlat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(42, 42, 42)
                .addComponent(registrarPlat, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cantIngP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agregarPlatIng)
                    .addComponent(exisIngP)
                    .addComponent(ings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(termPlatIng)
                    .addComponent(unidadIngP))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Agregar platillo", jPanel4);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        tPlatillos.setBackground(new java.awt.Color(139, 139, 244));
        tPlatillos.setForeground(new java.awt.Color(102, 102, 102));
        tPlatillos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tPlatillos);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Lista platillo", jPanel2);

        jPanel5.setBackground(new java.awt.Color(102, 102, 102));

        jLabel11.setFont(new java.awt.Font("Goudy Old Style", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 0));
        jLabel11.setText("Registrar platillo");

        jLabel16.setText("Nombre:");

        jLabel17.setText("Precio: ");

        jLabel18.setText("Existencias: ");

        nombrePlatEx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombrePlatExActionPerformed(evt);
            }
        });

        precioPlatEx.setModel(new javax.swing.SpinnerNumberModel(20.0d, 20.0d, 1000.0d, 1.0d));
        precioPlatEx.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        existenciasPlatEx.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
        existenciasPlatEx.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tiempoPEx.setModel(new javax.swing.SpinnerNumberModel(1, 1, 4, 1));

        porcionPEx.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        unidadMPEx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pza", "Kg", "Gr", "Litros", "Taza" }));

        jLabel21.setText("TIempo. ");

        jLabel22.setText("Porción:");

        jLabel23.setText("Unidad de medida:");

        jLabel19.setFont(new java.awt.Font("Goudy Old Style", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 0));
        jLabel19.setText("Especificación de las cantidades de los ingredientes del platillo");

        tPlatIngEx.setBackground(new java.awt.Color(255, 255, 153));
        tPlatIngEx.setForeground(new java.awt.Color(102, 102, 102));
        tPlatIngEx.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tPlatIngEx);

        regPlatEx.setBackground(new java.awt.Color(255, 255, 0));
        regPlatEx.setText("Registrar platillo");
        regPlatEx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regPlatExActionPerformed(evt);
            }
        });

        regPlatIngEx.setBackground(new java.awt.Color(255, 255, 0));
        regPlatIngEx.setForeground(new java.awt.Color(51, 51, 51));
        regPlatIngEx.setText("Registrar ingredientes");
        regPlatIngEx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regPlatIngExActionPerformed(evt);
            }
        });

        restaurarCant.setBackground(new java.awt.Color(255, 255, 0));
        restaurarCant.setForeground(new java.awt.Color(51, 51, 51));
        restaurarCant.setText("Iniciar cantidades(Restaurar)");
        restaurarCant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restaurarCantActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 46, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel23)
                            .addComponent(jLabel22)
                            .addComponent(jLabel21)
                            .addComponent(jLabel16)
                            .addComponent(jLabel18))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(nombrePlatEx, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                                .addComponent(porcionPEx, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(unidadMPEx, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tiempoPEx, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(precioPlatEx, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(existenciasPlatEx, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(140, 140, 140))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(regPlatEx)
                        .addGap(253, 253, 253))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(regPlatIngEx)
                        .addGap(40, 40, 40)
                        .addComponent(restaurarCant)
                        .addGap(118, 118, 118))))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(247, 247, 247)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addGap(119, 119, 119))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombrePlatEx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tiempoPEx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(porcionPEx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unidadMPEx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addGap(7, 7, 7)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(precioPlatEx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(existenciasPlatEx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(16, 16, 16)
                .addComponent(regPlatEx)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regPlatIngEx)
                    .addComponent(restaurarCant))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Agregar platillo Ex", jPanel5);

        jPanel6.setBackground(new java.awt.Color(153, 153, 153));

        tablaIng_Plat.setBackground(new java.awt.Color(255, 153, 255));
        tablaIng_Plat.setForeground(new java.awt.Color(102, 102, 102));
        tablaIng_Plat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tablaIng_Plat);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        jTabbedPane2.addTab("Ing_Plat", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreActionPerformed

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        //Agregar un ingrediente
        //System.out.println("Boton usado");
        ingrediente = new Ingrediente();// 
        //Obtener el valor de tipo de ingrediente
        tIngrediente = tiposIng.get(TipoIng.getSelectedIndex());

        //Asignar los atributos
        if (Nombre.getText() != null) { //Si tiene algo
            //Validar que el nombre del ingrediente no exista
            int ni = 0;
            //System.out.println(" valor  " + ni);
            for (; ni < Ingredientes.size() && !Nombre.getText().equalsIgnoreCase(Ingredientes.get(ni).getNombre()); ni++) {
                if (ni == Ingredientes.size() - 1) { //Si no esta
                    //System.out.println("Entro al if");
                    ingrediente.setNombre(Nombre.getText());
                    ingrediente.setCantidad((Double) Cantidad.getValue());
                    ingrediente.setTipoing(tIngrediente);
                    ingrediente.setUnidad(Unidad.getItemAt(Unidad.getSelectedIndex()));
                    cIngrediente.create(ingrediente);//GUardarlo en la tabla de la BD
                    Ingredientes.add(ingrediente);//Se agrega a la lista(memoria)
                    modeloIng.actualizarTamaño(Ingredientes.size());
                    ings.addItem(ingrediente.getNombre());
                    modeloIng.fireTableDataChanged();
                } else {
                    //System.out.println("Ya se encuentra");
                }
                //System.out.println("Termino el for");
            }
        } else {
            //System.out.println("Nombre nulo");
        }

        //System.out.println("Termino el uso del boton");
    }//GEN-LAST:event_agregarActionPerformed

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
       //para cambiar cantidad requerida
        for (int a = 0; a < tIngredientes.getRowCount(); a++) {
            if (tIngredientes.getValueAt(a, 4) != null && (Double) tIngredientes.getValueAt(a, 4) > 0.0) {
                if (Ingredientes.get(a).getCantidad() >= (Double) tIngredientes.getValueAt(a, 4)) {
                    //Ingredientes.get(a).setCantidad(Ingredientes.get(a).getCantidad() - (double) tIngredientes.getValueAt(a, 4));
                    try {
                        cIngrediente.edit(Ingredientes.get(a));
                    } catch (Exception ex) {

                    }
                }
            }
        }
    }//GEN-LAST:event_aceptarActionPerformed

    private void nombrePlatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombrePlatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombrePlatActionPerformed

    private void ingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingsActionPerformed
        //System.out.println(IngredientesJC.size() + "  ");
        try {
            if (agregarPlatIng.isEnabled() && IngredientesJC.size() > 0) {
                        //IngredientesJC = cIngrediente.findIngredienteEntities();
                exisIngP.setText(IngredientesJC.get(ings.getSelectedIndex()).getCantidad().toString());
                unidadIngP.setText(IngredientesJC.get(ings.getSelectedIndex()).getUnidad());
            } else {
                exisIngP.setText("_____");
                unidadIngP.setText("___");
            }
        } catch (ArrayIndexOutOfBoundsException e) {
            exisIngP.setText("_____");
            unidadIngP.setText("___");
        }

    }//GEN-LAST:event_ingsActionPerformed

    private void termPlatIngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_termPlatIngActionPerformed
        cPlatillo.create(platillo);//Guardarlo en la tabla de la BD
        platillos.add(platillo);//Se agrega a la lista(memoria)
        for (int a = 0; a < index.size(); a++) {

            try {
                cIngrediente.edit(index.get(a));
                //Ingredientes.get(ings.getSelectedIndex()).setCantidad(Ingredientes.get(ings.getSelectedIndex()).getCantidad() - (Double)cantIngP.getValue());
            } catch (Exception ex) {

            }
        }

        for (int b = Ingplatillos.size() - index.size(); b < Ingplatillos.size(); b++) {

            cIngPlatillo.create(Ingplatillos.get(b));
        }

        registrarPlat.setEnabled(true);
        agregarPlatIng.setEnabled(false);
        termPlatIng.setEnabled(false);
        ings.removeAllItems();
        for (int a = 0; a < Ingredientes.size(); a++) {
            ings.addItem(Ingredientes.get(a).getNombre());
        }
        modeloPlat.fireTableDataChanged();
        modeloIP.fireTableDataChanged();
        exisIngP.setText("_____");
        unidadIngP.setText("___");
    }//GEN-LAST:event_termPlatIngActionPerformed

    private void registrarPlatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarPlatActionPerformed
        //Agregar un ingrediente
        //System.out.println("Boton usado");
        platillo = new Platillo();
        //Obtener el valor de tipo de ingrediente
        //tIngrediente = tiposIng.get(TipoIng.getSelectedIndex());

        //Asignar los atributos
        if (nombrePlat.getText() != null) { //Si tiene algo
            //Validar que el nombre del ingrediente no exista
            int ni = 0;
            System.out.println(" valor  " + ni);
            for (; ni < platillos.size() && !nombrePlat.getText().equalsIgnoreCase(platillos.get(ni).getNombre()); ni++) {
                if (ni == platillos.size() - 1) { //Si no esta
                    System.out.println("Entro al if");
                    platillo.setNombre(nombrePlat.getText());
                    platillo.setTiempo((int) tiempoP.getValue());
                    platillo.setPrecio((Double) precioPlat.getValue());
                    platillo.setPorcion((int) porcionP.getValue());
                    platillo.setUnidaddm(unidadMP.getSelectedItem().toString());
                    platillo.setExistencia((int) existenciasPlat.getValue());
                    //cont = 0;
                    index = new ArrayList<>();
                    registrarPlat.setEnabled(false);
                    agregarPlatIng.setEnabled(true);
                    termPlatIng.setEnabled(true);

                    //cPlatillo.create(platillo);//Guardarlo en la tabla de la BD
                    //platillos.add(platillo);//Se agrega a la lista(memoria)
                    //modeloPlat.fireTableDataChanged();
                } else {
                   // System.out.println("Ya se encuentra");
                }
                //System.out.println("Termino el for");
            }
        } else {
            //System.out.println("Nombre nulo");
        }

        //System.out.println("Termino el uso del boton");


    }//GEN-LAST:event_registrarPlatActionPerformed

    private void agregarPlatIngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarPlatIngActionPerformed
        if (!registrarPlat.isEnabled() && IngredientesJC.size() > 0) {
            for (int e = 0; e < IngredientesJC.size(); e++) {
                if (ings.getSelectedItem().toString().equalsIgnoreCase(IngredientesJC.get(e).getNombre())
                        && (double) cantIngP.getValue() <= IngredientesJC.get(e).getCantidad()) {
                    ingPlatillo = new Ingpla();
                    ingPlatillo.setExistencia((Double) cantIngP.getValue());
                    ingPlatillo.setIding(IngredientesJC.get(ings.getSelectedIndex()));
                    ingPlatillo.setIdpla(platillo);
                    Ingplatillos.add(ingPlatillo);
                    IngredientesJC.get(e).setCantidad(IngredientesJC.get(e).getCantidad() - (Double) cantIngP.getValue());
                    index.add(IngredientesJC.get(e));
                    ings.removeItemAt(e);
                    IngredientesJC.remove(e);
                    //exisIngP.setText(Ingredientes.get(ings.getSelectedIndex()).getCantidad().toString());
                    if (IngredientesJC.size() > 0) {
                        ings.setSelectedIndex(0);
                    }
                } else {
                    if (e == IngredientesJC.size()) {
                        System.out.println("La cantidad solicitada es mayor a la existente");
                    }
                }
            }
        }
    }//GEN-LAST:event_agregarPlatIngActionPerformed

    private void nombrePlatExActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombrePlatExActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombrePlatExActionPerformed

    private void regPlatExActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regPlatExActionPerformed
        platillo = new Platillo();

        if (nombrePlatEx.getText() != null) { //Si tiene algo

            int ni = 0;
            System.out.println(" valor  " + ni);
            for (; ni < platillos.size() && !nombrePlatEx.getText().equalsIgnoreCase(platillos.get(ni).getNombre()); ni++) {
                if (ni == platillos.size() - 1) { //Si no esta
                    System.out.println("Entro al if");
                    platillo.setNombre(nombrePlatEx.getText());
                    platillo.setTiempo((int) tiempoPEx.getValue());
                    platillo.setPrecio((Double) precioPlatEx.getValue());
                    platillo.setPorcion((int) porcionPEx.getValue());
                    platillo.setUnidaddm(unidadMPEx.getSelectedItem().toString());
                    platillo.setExistencia((int) existenciasPlatEx.getValue());

                    temp = new ArrayList<>();
                    regPlatEx.setEnabled(false);
                    restaurarCant.setEnabled(true);
                    regPlatIngEx.setEnabled(true);
                    modeloIngEx.setTiempo((int) tiempoPEx.getValue());
                } else {
                    //System.out.println("Ya se encuentra");
                }
                //System.out.println("Termino el for");
            }
        } else {
            //System.out.println("Nombre nulo");
        }

        //System.out.println("Termino el uso del boton");
    }//GEN-LAST:event_regPlatExActionPerformed

    private void restaurarCantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restaurarCantActionPerformed
        modeloIngEx.rellenar();
        tPlatIngEx.setModel(modeloIngEx);
        tPlatIngEx.repaint();
    }//GEN-LAST:event_restaurarCantActionPerformed

    private void regPlatIngExActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regPlatIngExActionPerformed
                                           
        if (!regPlatEx.isEnabled()) {

            for (int e = 0; e < Ingredientes.size(); e++) {
                if ((Double) tPlatIngEx.getValueAt(e, 4) > 0) { //&& (Double)tPlatIngEx.getValueAt(4, e) < Ingredientes.get(e).getCantidad()){
                    ingPlatillo = new Ingpla();
                    ingPlatillo.setExistencia((Double) tPlatIngEx.getValueAt(e, 3));
                    ingPlatillo.setIding(Ingredientes.get(e));
                    ingPlatillo.setIdpla(platillo);
                    Ingplatillos.add(ingPlatillo);
                    temp.add(ingPlatillo);
                    Ingredientes.get(e).setCantidad(Ingredientes.get(e).getCantidad() - (Double) cantIngP.getValue());
                } else {
                    if (e == Ingredientes.size()) {
                        System.out.println("La cantidad solicitada es mayor a la existente");
                    }
                }
            }

        }
        cPlatillo.create(platillo);//Guardarlo en la tabla de la BD
        platillos.add(platillo);//Se agrega a la lista(memoria)
        for (int a = 0; a < Ingredientes.size(); a++) {
            if ((Double)tPlatIngEx.getValueAt(a, 3) > 0 && (Double)tPlatIngEx.getValueAt(a, 3) < Ingredientes.get(a).getCantidad()) {
                try {
                    cIngrediente.edit(Ingredientes.get(a));
                    //Ingredientes.get(ings.getSelectedIndex()).setCantidad(Ingredientes.get(ings.getSelectedIndex()).getCantidad() - (Double)cantIngP.getValue());
                } catch (Exception ex) {

                }
            }
        }
        for (int b = 0; b < temp.size(); b++) {
            cIngPlatillo.create(temp.get(b));
        }

        regPlatEx.setEnabled(true);
        restaurarCant.setEnabled(false);
        regPlatIngEx.setEnabled(false);

        modeloPlat.fireTableDataChanged();
    
        modeloIP.fireTableDataChanged();
    }//GEN-LAST:event_regPlatIngExActionPerformed

    private void TipoIngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoIngActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TipoIngActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Platillos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Platillos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Platillos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Platillos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Platillos dialog = new Platillos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner Cantidad;
    private javax.swing.JTextField Nombre;
    private javax.swing.JComboBox<String> TipoIng;
    private javax.swing.JComboBox<String> Unidad;
    private javax.swing.JButton aceptar;
    private javax.swing.JButton agregar;
    private javax.swing.JButton agregarPlatIng;
    private javax.swing.JSpinner cantIngP;
    private javax.swing.JLabel exisIngP;
    private javax.swing.JSpinner existenciasPlat;
    private javax.swing.JSpinner existenciasPlatEx;
    private javax.swing.JComboBox<String> ings;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField nombrePlat;
    private javax.swing.JTextField nombrePlatEx;
    private javax.swing.JSpinner porcionP;
    private javax.swing.JSpinner porcionPEx;
    private javax.swing.JSpinner precioPlat;
    private javax.swing.JSpinner precioPlatEx;
    private javax.swing.JButton regPlatEx;
    private javax.swing.JButton regPlatIngEx;
    private javax.swing.JButton registrarPlat;
    private javax.swing.JButton restaurarCant;
    private javax.swing.JTable tIngredientes;
    private javax.swing.JTable tPlatIngEx;
    private javax.swing.JTable tPlatillos;
    private javax.swing.JTable tablaIng_Plat;
    private javax.swing.JButton termPlatIng;
    private javax.swing.JSpinner tiempoP;
    private javax.swing.JSpinner tiempoPEx;
    private javax.swing.JLabel unidadIngP;
    private javax.swing.JComboBox<String> unidadMP;
    private javax.swing.JComboBox<String> unidadMPEx;
    // End of variables declaration//GEN-END:variables
}
